name: Publish Package to npmjs
on:
  push:
    branches:
      - main
  # release:
  #   types: [published]
jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write

    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: yarn
          registry-url: "https://registry.npmjs.org"
      - run: corepack enable
      - run: npm install -g npm yarn
      - run: yarn
      - name: Release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx semantic-release
